pipeline {
    agent any

    environment {
        dockerImageName = 'p27625' // ✅ Khai báo biến
    }

    stages {
        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/naruba200/MyDockerApp.git'
            }
        }

        stage('Clean bin/obj') {
            steps {
                bat 'rmdir /s /q MyDockerApp\\bin || echo bin not found'
                bat 'rmdir /s /q MyDockerApp\\obj || echo obj not found'
            }
        }

        stage('Restore & Build & Publish') {
            steps {
                bat 'dotnet clean'
                bat 'dotnet restore'
                bat 'dotnet build --configuration Release'
                bat 'dotnet publish MyDockerApp/MyDockerApp.csproj -c Release -o publish /p:DisableBuildStaticWebAssets=true'
            }
        }

        stage('Docker Build') {
            steps {
                bat "docker build -t ${dockerImageName}:latest -f \"MyDockerApp/Dockerfile\" MyDockerApp"
            }
        }

        stage('Docker Stop & Remove (nếu có)') {
            steps {
                bat '''
                @echo off
                for /f "delims=" %%i in ('docker ps -a --filter "name=p27625run" --format "{{.Names}}"') do (
                    set container=%%i
                )
                if defined container (
                    docker stop p27625run >nul 2>&1
                    docker rm p27625run >nul 2>&1
                )
                '''
            }
        }

        stage('Docker Run') {
            steps {
                bat 'docker run -d --name p27625run -p 91:3000 p27625:latest'
            }
        }
    }
}
