apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
spec:
  type: NodePort
  selector:
    app: dotnet-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30091
